package uk.gov.nationalarchives.db

import slick.jdbc.PostgresProfile.api._
import slick.lifted.{ProvenShape, TableQuery}
import uk.gov.nationalarchives.model.Consignment

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

class ConsignmentDao {
  // Slick requires every non-nullable column to have a value on insert, even the ID column, so provide an arbitrary
  // ID which will be overwritten by the auto-incrementing value generated by PostgreSQL
  private val dummyId = 0

  // Load PostgreSQL driver into classpath
  Class.forName("org.postgresql.Driver")

  private val dbConfig = sys.env.get("TDR_API_ENVIRONMENT") match {
    case Some("TEST") => PrototypeDbConfig
    case _ => DevDbConfig
  }

  private val db = Database.forURL(
    url = dbConfig.url,
    user = dbConfig.username,
    password = dbConfig.password,
    driver = "org.postgresql.Driver"
  )

  private val consignments = TableQuery[Consignments]

  private val insertQuery = consignments returning consignments.map(_.id) into ((consignment, id) => consignment.copy(id = Some(id)))

  def all: Future[Seq[Consignment]] = {
    db.run(consignments.result)
  }

  def get(id: Int): Future[Option[Consignment]] = {
    db.run(consignments.filter(_.id === id).result).map(_.headOption)
  }

  def create(consignment: Consignment): Future[Consignment] = {
    db.run(insertQuery += consignment)
  }
}

class Consignments(tag: Tag) extends Table[Consignment](tag, "consignments") {
  def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
  def name = column[String]("name")

  override def * : ProvenShape[Consignment] = (id.?, name).mapTo[Consignment]
}